import { randomBytes } from "node:crypto";
import path from "node:path";

// Attachment rules — BR-29 through BR-33.
//
// The frontend checks these too, for immediate feedback. This module is the
// authoritative layer: nothing reaches storage without passing it.

/** BR-29 — permitted types. */
export const ALLOWED_MIME_TYPES: Record<string, string[]> = {
  "image/jpeg": [".jpg", ".jpeg"],
  "image/png": [".png"],
  "image/webp": [".webp"],
  "application/pdf": [".pdf"],
};

export const ALLOWED_EXTENSIONS = Object.values(ALLOWED_MIME_TYPES).flat();

/** BR-30 — 5 MB per file. */
export const MAX_FILE_SIZE_BYTES = 5 * 1024 * 1024;

/** BR-31 — at most five active attachments per ticket. */
export const MAX_ACTIVE_ATTACHMENTS = 5;

/**
 * BR-29 — a file is permitted only when its declared type is on the list AND
 * its extension matches that type. Checking both stops a .exe renamed to .png
 * (or a PDF declared as an image) from slipping through on one signal alone.
 */
export function isPermittedFile(mimeType: string, originalFilename: string): boolean {
  const extensions = ALLOWED_MIME_TYPES[mimeType.toLowerCase()];
  if (!extensions) return false;

  const ext = path.extname(originalFilename).toLowerCase();
  return extensions.includes(ext);
}

/**
 * BR-33 — the stored name is generated by the server and never derived from
 * the untrusted original filename, so a crafted name cannot escape the upload
 * directory or overwrite another file.
 */
export function generateStorageKey(originalFilename: string): string {
  const ext = path.extname(originalFilename).toLowerCase();
  const safeExt = ALLOWED_EXTENSIONS.includes(ext) ? ext : "";
  return `${Date.now().toString(36)}-${randomBytes(16).toString("hex")}${safeExt}`;
}

/**
 * BR-33 — the original filename is display metadata. Strip anything that
 * could be read as a path or break the Content-Disposition header before
 * echoing it back to a browser.
 */
export function safeDisplayFilename(originalFilename: string): string {
  const base = path.basename(originalFilename).replace(/[\r\n"\\]/g, "");
  const cleaned = base.replace(/[\u0000-\u001f\u007f]/g, "").trim();
  return cleaned.length > 0 ? cleaned.slice(0, 255) : "attachment";
}

/** BR-35 — soft removal requires a non-empty reason. */
export const MAX_REMOVAL_REASON_LENGTH = 500;

export function validateRemovalReason(value: unknown): {
  reason?: string;
  error?: string;
} {
  if (typeof value !== "string" || value.trim().length === 0) {
    return { error: "A removal reason is required." };
  }
  const reason = value.trim();
  if (reason.length > MAX_REMOVAL_REASON_LENGTH) {
    return {
      error: `Removal reason must be ${MAX_REMOVAL_REASON_LENGTH} characters or fewer.`,
    };
  }
  return { reason };
}
