// BR-01 — the official Ticket Number is generated by the backend and must be
// unique. Uniqueness is ultimately enforced by the database
// (Ticket.ticketNumber is UNIQUE); this module produces the human-readable
// value and the caller retries when two requests race for the same sequence.

export const TICKET_NUMBER_PREFIX = "TT";
const SEQUENCE_DIGITS = 4;

/** Local-date stamp, e.g. 20260905. Ticket Dates are read in local time. */
export function ticketNumberDateStamp(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}${month}${day}`;
}

/** The shared prefix for every Ticket Number issued on `date`, e.g. TT-20260905-. */
export function ticketNumberPrefixFor(date: Date): string {
  return `${TICKET_NUMBER_PREFIX}-${ticketNumberDateStamp(date)}-`;
}

/** Builds a full Ticket Number, e.g. TT-20260905-0001. */
export function formatTicketNumber(date: Date, sequence: number): string {
  const padded = String(sequence).padStart(SEQUENCE_DIGITS, "0");
  return `${ticketNumberPrefixFor(date)}${padded}`;
}

/**
 * Reads the sequence back out of a Ticket Number, or null when the value does
 * not match the documented format.
 */
export function parseTicketNumberSequence(ticketNumber: string): number | null {
  const match = new RegExp(
    `^${TICKET_NUMBER_PREFIX}-\\d{8}-(\\d{${SEQUENCE_DIGITS},})$`,
  ).exec(ticketNumber);
  if (!match) return null;
  return Number.parseInt(match[1], 10);
}

/** Next sequence for the day, given the highest Ticket Number issued so far. */
export function nextSequence(latestTicketNumber: string | null): number {
  if (latestTicketNumber === null) return 1;
  const current = parseTicketNumberSequence(latestTicketNumber);
  return current === null ? 1 : current + 1;
}
